In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Perceptron

# %matplotlib inline

In [9]:
dataset = pd.read_csv("/content/drive/MyDrive/bt/gender_classification_v7.csv")
dataset.head(10)

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female
5,1,13.0,6.8,1,1,1,1,Male
6,1,15.3,6.2,1,1,1,0,Male
7,0,13.0,5.2,0,0,0,0,Female
8,1,11.9,5.4,1,0,1,1,Female
9,1,12.1,5.4,0,0,0,0,Female

In [12]:
dataset = dataset.replace("Male" , 1 )
dataset = dataset.replace("Female" , 0 )
dataset

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,1
1,0,14.0,5.4,0,0,1,0,0
2,0,11.8,6.3,1,1,1,1,1
3,0,14.4,6.1,0,1,1,1,1
4,1,13.5,5.9,0,0,0,0,0
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,0
4997,1,11.9,5.4,0,0,0,0,0
4998,1,12.9,5.7,0,0,0,0,0
4999,1,13.2,6.2,0,0,0,0,0
5000,1,15.4,5.4,1,1,1,1,1

In [18]:
# make perceptron object (m_perceptron)
m_perceptron = Perceptron(max_iter=10000, verbose=0, random_state=None, fit_intercept=True, eta0=0.001)

# train the perceptron object (m_perceptron)
m_perceptron.fit(dataset[['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long' ]],dataset['gender'])

# print the coefficients matrix and bias
coefficients = m_perceptron.coef_;
bias = m_perceptron.intercept_;
print ("coefficients = " + str(coefficients))
print ("bias = " + str(bias))

coefficients = [[-0.045   0.0019 -0.0196  0.194   0.174   0.176   0.188 ]]
bias = [-0.087]

In [19]:
# run prediction for all the values in the dataset
prediction = m_perceptron.predict(dataset[['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long']])
print (prediction)

[1 1 1 ... 0 0 1]

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(prediction, dataset['gender'])

0.9432113577284543